# Generated by Django 3.2.5 on 2021-12-11 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('starting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participarnts',
            field=models.ManyToManyField(blank=True, related_name='participarnts', to=settings.AUTH_USER_MODEL),
        ),
    ]
